version: '3.8'

services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    hostname: minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - minio-net
    command: server /data --console-address ":9001"
    labels:
      - "traefik.enable=true"
      
      # Routing for image retrieval (GET requests)
      - "traefik.http.routers.minio.rule=Host(`cdn.dennishilhorst.nl`) && Method(`GET`)"
      - "traefik.http.routers.minio.middlewares=block-uploads@docker"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.tls.certresolver=myresolver"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

      # Routing for MinIO console
      - "traefik.http.routers.minio-console.rule=Host(`cdn.console.dennishilhorst.nl`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.tls.certresolver=myresolver"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
volumes:
  minio-data:
networks:
  minio-net:
    name: minio-net
    driver: bridge